
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: recording

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

recording: ../../../include/eib7.h recording.c
	gcc $(CFLAGS) -o recording recording.c $(EIBLIB) $(LIBS)
	    