
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: pulscounter

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

pulscounter: ../../../include/eib7.h pulscounter.c
	gcc $(CFLAGS) -o pulscounter pulscounter.c $(EIBLIB) $(LIBS)
	    