
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: softrealtime_endat_ai

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

softrealtime_endat_ai: ../../../include/eib7.h softrealtime_endat_ai.c
	gcc $(CFLAGS) -o softrealtime_endat_ai softrealtime_endat_ai.c $(EIBLIB) $(LIBS)
	    