
EIBLIB=..\..\..\lib\eib7.lib

INC=/I..\..\..\include /I.

DEBUG=/Zi

CFLAGS=/nologo /c $(INC) $(DEBUG) /DWin32

LIBS=user32.lib ws2_32.lib kernel32.lib


ALL: callback.exe

#
#
# cleanup targets
#
#

clean:
	del /q *.obj

distclean: clean
	del /q *.obj *.exe


#
#
# executables
#
#

callback.obj: ..\..\..\include\eib7.h callback.c
callback.exe: $(EIBLIB) callback.obj
	cl  $(DEBUG) /o callback.exe callback.obj $(EIBLIB) $(LIBS)
