
EIBLIB=..\..\..\lib\eib7.lib

INC=/I..\..\..\include /I.

DEBUG=/Zi

CFLAGS=/nologo /c $(INC) $(DEBUG) /DWin32

LIBS=user32.lib ws2_32.lib kernel32.lib


ALL: pulscounter.exe

#
#
# cleanup targets
#
#

clean:
	del /q *.obj

distclean: clean
	del /q *.obj *.exe


#
#
# executables
#
#

pulscounter.obj: ..\..\..\include\eib7.h pulscounter.c
pulscounter.exe: $(EIBLIB) pulscounter.obj
	cl  $(DEBUG) /o pulscounter.exe pulscounter.obj $(EIBLIB) $(LIBS)
