
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: callback

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

callback: ../../../include/eib7.h callback.c
	gcc $(CFLAGS) -o callback callback.c $(EIBLIB) $(LIBS)
	    