
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: matchIncrEnDat

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

matchIncrEnDat: ../../../include/eib7.h matchIncrEnDat.c
	gcc $(CFLAGS) -o matchIncrEnDat matchIncrEnDat.c $(EIBLIB) $(LIBS)
	    