
EIBLIB=..\..\..\lib\eib7.lib

INC=/I..\..\..\include /I.

DEBUG=/Zi

CFLAGS=/nologo /c $(INC) $(DEBUG) /DWin32

LIBS=user32.lib ws2_32.lib kernel32.lib


ALL: recording.exe

#
#
# cleanup targets
#
#

clean:
	del /q *.obj

distclean: clean
	del /q *.obj *.exe


#
#
# executables
#
#

recording.obj: ..\..\..\include\eib7.h recording.c
recording.exe: $(EIBLIB) recording.obj
	cl  $(DEBUG) /o recording.exe recording.obj $(EIBLIB) $(LIBS)
