
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: softrealtime_endat

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

softrealtime_endat: ../../../include/eib7.h softrealtime_endat.c
	gcc $(CFLAGS) -o softrealtime_endat softrealtime_endat.c $(EIBLIB) $(LIBS)
	    