
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: softrealtime

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

softrealtime: ../../../include/eib7.h softrealtime.c
	gcc $(CFLAGS) -o softrealtime softrealtime.c $(EIBLIB) $(LIBS)
	    