
EIBLIB=..\..\..\lib\eib7.lib

INC=/I..\..\..\include /I.

DEBUG=/Zi

CFLAGS=/nologo /c $(INC) $(DEBUG) /DWin32

LIBS=user32.lib ws2_32.lib kernel32.lib


ALL: easy.exe

#
#
# cleanup targets
#
#

clean:
	del /q *.obj

distclean: clean
	del /q *.obj *.exe


#
#
# executables
#
#

easy.obj: ..\..\..\include\eib7.h easy.c
easy.exe: $(EIBLIB) easy.obj
	cl  $(DEBUG) /o easy.exe easy.obj $(EIBLIB) $(LIBS)
