
EIBLIB=..\..\..\lib\eib7.lib

INC=/I..\..\..\include /I.

DEBUG=/Zi

CFLAGS=/nologo /c $(INC) $(DEBUG) /DWin32

LIBS=user32.lib ws2_32.lib kernel32.lib


ALL: trigger_io.exe

#
#
# cleanup targets
#
#

clean:
	del /q *.obj

distclean: clean
	del /q *.obj *.exe


#
#
# executables
#
#

trigger_io.obj: ..\..\..\include\eib7.h trigger_io.c
trigger_io.exe: $(EIBLIB) trigger_io.obj
	cl  $(DEBUG) /o trigger_io.exe trigger_io.obj $(EIBLIB) $(LIBS)
