
EIBLIB=-L . -leib7

INC=-I../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: networksettings

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

networksettings: ../../include/eib7.h networksettings.c
	gcc $(CFLAGS) -o networksettings networksettings.c $(EIBLIB) $(LIBS)
	    