
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: streaming

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

streaming: ../../../include/eib7.h streaming.c
	gcc $(CFLAGS) -o streaming streaming.c $(EIBLIB) $(LIBS)
	    