
EIBLIB=..\..\..\lib\eib7.lib

INC=/I..\..\..\include /I.

DEBUG=/Zi

CFLAGS=/nologo /c $(INC) $(DEBUG) /DWin32

LIBS=user32.lib ws2_32.lib kernel32.lib


ALL: fourheadsystem.exe

#
#
# cleanup targets
#
#

clean:
	del /q *.obj

distclean: clean
	del /q *.obj *.exe


#
#
# executables
#
#

fourheadsystem.obj: ..\..\..\include\eib7.h fourheadsystem.c
fourheadsystem.exe: $(EIBLIB) fourheadsystem.obj
	cl  $(DEBUG) /o fourheadsystem.exe fourheadsystem.obj $(EIBLIB) $(LIBS)
