
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: intervalcounter

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

intervalcounter: ../../../include/eib7.h intervalcounter.c
	gcc $(CFLAGS) -o intervalcounter intervalcounter.c $(EIBLIB) $(LIBS)
	    