
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: fourheadsystem

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

fourheadsystem: ../../../include/eib7.h fourheadsystem.c
	gcc $(CFLAGS) -o fourheadsystem fourheadsystem.c $(EIBLIB) $(LIBS)
	    