
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: easy

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

easy: ../../../include/eib7.h easy.c
	gcc $(CFLAGS) -o easy easy.c $(EIBLIB) $(LIBS)
	    