
EIBLIB=-L . -leib7

INC=-I../../../include

DEBUG=-g

CFLAGS=$(INC) $(DEBUG) -DLinux

LIBS=-lpthread


ALL: trigger_ri

#
#
# cleanup targets
#
#

clean:
	rm -f *.o

distclean: clean
	rm -f *.o

#
#
# executables
#
#

trigger_ri: ../../../include/eib7.h trigger_ri.c
	gcc $(CFLAGS) -o trigger_ri trigger_ri.c $(EIBLIB) $(LIBS)
	    